/*
 * Copyright (c) 2026 Rubus Technologies Inc.
 *
 * SPDX-License-Identifier: Apache-2.0
 */

#ifndef MOTOR_CONTROL_LOOP_H_
#define MOTOR_CONTROL_LOOP_H_

#include <stdbool.h>
#include <stdint.h>
#include <zephyr/dsp/types.h>
#include <zephyr/dsp/utils.h>

struct motor_parameters;

/**
 * @brief Encoder sample input prepared by ISR I/O glue.
 */
struct motor_control_encoder_sample {
	bool enabled;
	bool fresh;
	bool warning;
	bool error;
	bool io_fault;
	uint8_t status;
	float32_t angle_deg;
};

/**
 * @brief PWM command result generated by one control-loop iteration.
 */
struct motor_control_pwm_output {
	bool update_pwm;
	float32_t da_hb1_pu;
	float32_t da_hb2_pu;
	float32_t db_hb1_pu;
	float32_t db_hb2_pu;
};

/**
 * @brief Execute one pure motor-control loop iteration from sampled ADC values.
 *
 * This function runs control math/state updates only and does not touch devices.
 * PWM outputs are returned in @p pwm_out when @p update_pwm is true.
 */
void motor_control_loop_step(struct motor_parameters *params,
			     const q31_t *values,
			     uint8_t count,
			     const struct motor_control_encoder_sample *encoder_sample,
			     struct motor_control_pwm_output *pwm_out);

#endif /* MOTOR_CONTROL_LOOP_H_ */
