# SPDX-License-Identifier: Apache-2.0
#
# Hardware-in-loop serial shell settings.
#
# Use this for real motor tests where command reliability matters but full
# debug logging/debug compiler settings are not desired.

CONFIG_SHELL_CMD_BUFF_SIZE=512
CONFIG_SHELL_HISTORY_BUFFER=1024
CONFIG_SHELL_BACKEND_SERIAL_RX_RING_BUFFER_SIZE=8192
